[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
geo = { version = "0.29.3", default-features = false, features = ["use-serde"] }
glam = { version = "0.29", features = ["serde"] }
serde = { version = "1.0", default-features = false, features = ["derive", "std"] }
