[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
glam = { version = "0.29", features = ["serde"] }
serde = { version = "1.0", default-features = false, features = ["derive", "std"] }
